[theme]
# Primary accent color for interactive elements.
primaryColor = "#fff"

# Background color for the main content area.
backgroundColor = "#F8FBF8"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#7eca2c"

# Color used for almost all text.
textColor = "#000000"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"

